"""empty message

Revision ID: 6477e673f59a
Revises: 59443c871857
Create Date: 2021-05-22 17:23:13.241607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6477e673f59a'
down_revision = '59443c871857'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_coin_state_is_holding'), 'coin_state', ['is_holding'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coin_state_is_holding'), table_name='coin_state')
    # ### end Alembic commands ###
