"""add audit table

Revision ID: 8b2df8d786bc
Revises: 6477e673f59a
Create Date: 2021-05-23 11:41:30.992907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b2df8d786bc'
down_revision = '6477e673f59a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occured_at', sa.DateTime(), nullable=True),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('client_order_id', sa.String(length=100), nullable=False),
    sa.Column('orig_qty', sa.Float(), nullable=False),
    sa.Column('executed_qty', sa.Float(), nullable=False),
    sa.Column('cummulative_quote_qty', sa.Float(), nullable=False),
    sa.Column('order_status', sa.String(length=50), nullable=False),
    sa.Column('time_in_force', sa.String(length=10), nullable=False),
    sa.Column('order_type', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('fills', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions_audit')
    # ### end Alembic commands ###
