"""update coin log table

Revision ID: a606ef4069c0
Revises: e292d329d9e0
Create Date: 2021-06-01 09:41:45.191114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a606ef4069c0'
down_revision = 'e292d329d9e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incoming_coin_log', sa.Column(
        't1', sa.Boolean(), nullable=True))
    op.add_column('incoming_coin_log', sa.Column(
        't2', sa.Boolean(), nullable=True))
    op.add_column('incoming_coin_log', sa.Column(
        't3', sa.Boolean(), nullable=True))
    op.add_column('incoming_coin_log', sa.Column(
        't4', sa.Boolean(), nullable=True))
    op.add_column('incoming_coin_log', sa.Column(
        'price', sa.Float(), nullable=True))
    op.drop_column('incoming_coin_log', 'incoming_trigger')
    op.drop_column('incoming_coin_log', 'trigger_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incoming_coin_log', sa.Column('trigger_status',
                  sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('incoming_coin_log', sa.Column('incoming_trigger',
                  sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.drop_column('incoming_coin_log', 'price')
    op.drop_column('incoming_coin_log', 't4')
    op.drop_column('incoming_coin_log', 't3')
    op.drop_column('incoming_coin_log', 't2')
    op.drop_column('incoming_coin_log', 't1')
    # ### end Alembic commands ###
