"""add T3 and T4 columns

Revision ID: e292d329d9e0
Revises: 8b2df8d786bc
Create Date: 2021-05-31 19:51:44.601507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e292d329d9e0'
down_revision = '8b2df8d786bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coin_state', sa.Column('trigger_three_status', sa.Boolean(), nullable=True))
    op.add_column('coin_state', sa.Column('trigger_four_status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coin_state', 'trigger_four_status')
    op.drop_column('coin_state', 'trigger_three_status')
    # ### end Alembic commands ###
